import type { editor } from 'monaco-editor';

export const forgeDarkTheme: editor.IStandaloneThemeData = {
  base: 'vs-dark',
  inherit: true,
  rules: [
    { token: 'comment', foreground: '6A737D', fontStyle: 'italic' },
    { token: 'keyword', foreground: 'F97583' },
    { token: 'string', foreground: '9ECBFF' },
    { token: 'number', foreground: '79B8FF' },
    { token: 'type', foreground: 'B392F0' },
    { token: 'function', foreground: 'B392F0' },
    { token: 'variable', foreground: 'E1E4E8' },
    { token: 'constant', foreground: '79B8FF' },
    { token: 'parameter', foreground: 'FFAB70' },
    { token: 'property', foreground: '79B8FF' },
    { token: 'punctuation', foreground: 'E1E4E8' },
    { token: 'operator', foreground: 'F97583' },
    { token: 'namespace', foreground: 'B392F0' },
    { token: 'class', foreground: 'F97583' },
    { token: 'interface', foreground: 'B392F0' },
    { token: 'support', foreground: '79B8FF' },
  ],
  colors: {
    'editor.background': '#0d1117',
    'editor.foreground': '#e1e4e8',
    'editor.lineHighlightBackground': '#161b22',
    'editor.selectionBackground': '#264f78',
    'editor.inactiveSelectionBackground': '#264f7855',
    'editorCursor.foreground': '#58a6ff',
    'editorWhitespace.foreground': '#444d56',
    'editorIndentGuide.background': '#30363d',
    'editorIndentGuide.activeBackground': '#444d56',
    'editor.selectionHighlightBackground': '#36525f55',
    'editor.findMatchBackground': '#9e6a0355',
    'editor.findMatchHighlightBackground': '#f2cc6055',
    'editorBracketMatch.background': '#17E5E650',
    'editorBracketMatch.border': '#17E5E600',
    'editorGutter.background': '#0d1117',
    'editorLineNumber.foreground': '#444d56',
    'editorLineNumber.activeForeground': '#e1e4e8',
    'editorError.foreground': '#f85149',
    'editorWarning.foreground': '#f0883e',
    'editorInfo.foreground': '#58a6ff',
    'scrollbar.shadow': '#0008',
    'scrollbarSlider.background': '#484f5833',
    'scrollbarSlider.hoverBackground': '#484f5844',
    'scrollbarSlider.activeBackground': '#484f5888',
    'editorOverviewRuler.border': '#010409',
    'panel.background': '#010409',
    'panel.border': '#30363d',
    'panelTitle.activeBorder': '#f78166',
    'panelTitle.activeForeground': '#e1e4e8',
    'panelTitle.inactiveForeground': '#8b949e',
    'terminal.ansiBlack': '#484f58',
    'terminal.ansiRed': '#ff7b72',
    'terminal.ansiGreen': '#3fb950',
    'terminal.ansiYellow': '#d29922',
    'terminal.ansiBlue': '#58a6ff',
    'terminal.ansiMagenta': '#bc8cff',
    'terminal.ansiCyan': '#39c5cf',
    'terminal.ansiWhite': '#b1bac4',
    'terminal.ansiBrightBlack': '#6e7681',
    'terminal.ansiBrightRed': '#ffa198',
    'terminal.ansiBrightGreen': '#56d364',
    'terminal.ansiBrightYellow': '#e3b341',
    'terminal.ansiBrightBlue': '#79c0ff',
    'terminal.ansiBrightMagenta': '#d2a8ff',
    'terminal.ansiBrightCyan': '#56d4dd',
    'terminal.ansiBrightWhite': '#f0f6fc',
    'gitDecoration.addedResourceForeground': '#3fb950',
    'gitDecoration.modifiedResourceForeground': '#d29922',
    'gitDecoration.deletedResourceForeground': '#f85149',
    'gitDecoration.untrackedResourceForeground': '#3fb950',
    'gitDecoration.ignoredResourceForeground': '#484f58',
    'gitDecoration.conflictingResourceForeground': '#db6d28',
    'gitDecoration.submoduleResourceForeground': '#8b949e',
    'debugToolBar.background': '#161b22',
    'editorGroupHeader.tabsBackground': '#010409',
    'tab.activeBackground': '#0d1117',
    'tab.activeBorder': '#0d1117',
    'tab.activeBorderTop': '#f78166',
    'tab.activeForeground': '#e1e4e8',
    'tab.border': '#30363d',
    'tab.hoverBackground': '#0d1117',
    'tab.inactiveBackground': '#010409',
    'tab.unfocusedHoverBackground': '#161b2288',
    'tab.inactiveForeground': '#8b949e',
    'tab.unfocusedActiveBorderTop': '#30363d',
    'tab.unfocusedInactiveForeground': '#8b949e',
    'editorWidget.background': '#161b22',
    'editorWidget.border': '#30363d',
    'editorSuggestWidget.background': '#161b22',
    'editorSuggestWidget.border': '#30363d',
    'editorSuggestWidget.foreground': '#e1e4e8',
    'editorSuggestWidget.highlightForeground': '#58a6ff',
    'editorSuggestWidget.selectedBackground': '#30363d',
    'editorHoverWidget.background': '#161b22',
    'editorHoverWidget.border': '#30363d',
    'editorHoverWidget.foreground': '#e1e4e8',
    'debugExceptionWidget.background': '#161b22',
    'debugExceptionWidget.border': '#a40e26',
    'editorMarkerNavigation.background': '#161b22',
    'editorMarkerNavigationError.background': '#f8514966',
    'editorMarkerNavigationWarning.background': '#f0883e66',
    'editorMarkerNavigationInfo.background': '#58a6ff66',
    'dropdown.background': '#161b22',
    'dropdown.border': '#30363d',
    'dropdown.foreground': '#e1e4e8',
    'dropdown.listBackground': '#161b22',
    'input.background': '#0d1117',
    'input.border': '#30363d',
    'input.foreground': '#e1e4e8',
    'input.placeholderForeground': '#484f58',
    'inputOption.activeBackground': '#1f6feb66',
    'inputOption.activeBorder': '#1f6feb',
    'inputValidation.errorBackground': '#f8514966',
    'inputValidation.errorBorder': '#f85149',
    'inputValidation.errorForeground': '#e1e4e8',
    'inputValidation.infoBackground': '#0c2d6b66',
    'inputValidation.infoBorder': '#0c2d6b',
    'inputValidation.infoForeground': '#e1e4e8',
    'inputValidation.warningBackground': '#bb800966',
    'inputValidation.warningBorder': '#bb8009',
    'inputValidation.warningForeground': '#e1e4e8',
    'list.hoverBackground': '#161b22',
    'list.inactiveSelectionBackground': '#161b22',
    'list.activeSelectionBackground': '#1f6feb33',
    'list.focusBackground': '#1f6feb33',
    'list.focusForeground': '#e1e4e8',
    'list.highlightForeground': '#58a6ff',
    'list.dropBackground': '#1f6feb33',
    'list.errorForeground': '#f85149',
    'list.warningForeground': '#f0883e',
    'minimap.background': '#010409',
    'minimap.findMatchHighlight': '#f2cc6088',
    'minimap.selectionHighlight': '#264f78',
    'minimap.errorHighlight': '#f85149',
    'minimap.warningHighlight': '#f0883e',
    'minimapGutter.addedBackground': '#3fb950',
    'minimapGutter.modifiedBackground': '#d29922',
    'minimapGutter.deletedBackground': '#f85149',
    'peekView.border': '#1f6feb',
    'peekViewEditor.background': '#0a0c10',
    'peekViewEditor.matchHighlightBackground': '#f2cc6066',
    'peekViewResult.background': '#0a0c10',
    'peekViewResult.fileForeground': '#e1e4e8',
    'peekViewResult.lineForeground': '#8b949e',
    'peekViewResult.matchHighlightBackground': '#f2cc6066',
    'peekViewResult.selectionBackground': '#1f6feb33',
    'peekViewResult.selectionForeground': '#e1e4e8',
    'peekViewTitle.background': '#161b22',
    'peekViewTitleDescription.foreground': '#8b949e',
    'peekViewTitleLabel.foreground': '#e1e4e8',
    'pickerGroup.border': '#30363d',
    'pickerGroup.foreground': '#8b949e',
    'quickInput.background': '#161b22',
    'quickInput.foreground': '#e1e4e8',
    'statusBar.background': '#0d1117',
    'statusBar.foreground': '#8b949e',
    'statusBar.border': '#30363d',
    'statusBar.noFolderBackground': '#0d1117',
    'statusBar.debuggingBackground': '#da3633',
    'statusBar.debuggingForeground': '#f0f6fc',
    'statusBarItem.activeBackground': '#1f232833',
    'statusBarItem.hoverBackground': '#1f232844',
    'statusBarItem.prominentBackground': '#161b22',
    'statusBarItem.prominentForeground': '#e1e4e8',
    'statusBarItem.prominentHoverBackground': '#30363d',
    'statusBarItem.remoteBackground': '#1f6feb',
    'statusBarItem.remoteForeground': '#f0f6fc',
    'titleBar.activeBackground': '#0d1117',
    'titleBar.activeForeground': '#e1e4e8',
    'titleBar.border': '#30363d',
    'titleBar.inactiveBackground': '#010409',
    'titleBar.inactiveForeground': '#8b949e',
    'menubar.selectionForeground': '#e1e4e8',
    'menubar.selectionBackground': '#1f232855',
    'menubar.selectionBorder': '#1f232800',
    'menu.foreground': '#e1e4e8',
    'menu.background': '#161b22',
    'menu.selectionForeground': '#e1e4e8',
    'menu.selectionBackground': '#1f6feb33',
    'menu.selectionBorder': '#1f6feb00',
    'menu.separatorBackground': '#30363d',
    'menu.border': '#30363d00',
    'button.background': '#238636',
    'button.foreground': '#ffffff',
    'button.hoverBackground': '#2ea043',
    'button.secondaryBackground': '#30363d',
    'button.secondaryForeground': '#e1e4e8',
    'button.secondaryHoverBackground': '#484f58',
    'checkbox.background': '#161b22',
    'checkbox.border': '#30363d',
    'checkbox.foreground': '#e1e4e8',
    'textLink.foreground': '#58a6ff',
    'textLink.activeForeground': '#58a6ff',
    'textCodeBlock.background': '#6e768166',
    'textBlockQuote.background': '#010409',
    'textBlockQuote.border': '#30363d',
    'textPreformat.foreground': '#8b949e',
  },
};

export const forgeLightTheme: editor.IStandaloneThemeData = {
  base: 'vs',
  inherit: true,
  rules: [
    { token: 'comment', foreground: '6A737D', fontStyle: 'italic' },
    { token: 'keyword', foreground: 'D73A49' },
    { token: 'string', foreground: '032F62' },
    { token: 'number', foreground: '005CC5' },
    { token: 'type', foreground: '6F42C1' },
    { token: 'function', foreground: '6F42C1' },
    { token: 'variable', foreground: '24292E' },
    { token: 'constant', foreground: '005CC5' },
    { token: 'parameter', foreground: 'E36209' },
    { token: 'property', foreground: '005CC5' },
    { token: 'punctuation', foreground: '24292E' },
    { token: 'operator', foreground: 'D73A49' },
    { token: 'namespace', foreground: '6F42C1' },
    { token: 'class', foreground: 'D73A49' },
    { token: 'interface', foreground: '6F42C1' },
    { token: 'support', foreground: '005CC5' },
  ],
  colors: {
    'editor.background': '#ffffff',
    'editor.foreground': '#24292e',
    'editor.lineHighlightBackground': '#f6f8fa',
    'editor.selectionBackground': '#c8d1f8',
    'editor.inactiveSelectionBackground': '#e1e4e8',
    'editorCursor.foreground': '#0969da',
    'editorWhitespace.foreground': '#d1d5da',
    'editorIndentGuide.background': '#eff2f6',
    'editorIndentGuide.activeBackground': '#d1d5da',
    'editor.selectionHighlightBackground': '#fed33a40',
    'editor.findMatchBackground': '#ffdf5d66',
    'editor.findMatchHighlightBackground': '#ffdf5d33',
    'editorBracketMatch.background': '#34d05840',
    'editorBracketMatch.border': '#34d05800',
    'editorGutter.background': '#ffffff',
    'editorLineNumber.foreground': '#959da5',
    'editorLineNumber.activeForeground': '#24292e',
    'editorError.foreground': '#d73a49',
    'editorWarning.foreground': '#e36209',
    'editorInfo.foreground': '#0969da',
    'scrollbar.shadow': '#6a737d33',
    'scrollbarSlider.background': '#959da533',
    'scrollbarSlider.hoverBackground': '#959da544',
    'scrollbarSlider.activeBackground': '#959da588',
    'editorOverviewRuler.border': '#ffffff',
    'panel.background': '#f6f8fa',
    'panel.border': '#e1e4e8',
    'panelTitle.activeBorder': '#f9826c',
    'panelTitle.activeForeground': '#24292e',
    'panelTitle.inactiveForeground': '#6a737d',
    'terminal.ansiBlack': '#24292e',
    'terminal.ansiRed': '#d73a49',
    'terminal.ansiGreen': '#28a745',
    'terminal.ansiYellow': '#dbab09',
    'terminal.ansiBlue': '#0366d6',
    'terminal.ansiMagenta': '#5a32a3',
    'terminal.ansiCyan': '#0598bc',
    'terminal.ansiWhite': '#6a737d',
    'terminal.ansiBrightBlack': '#959da5',
    'terminal.ansiBrightRed': '#cb2431',
    'terminal.ansiBrightGreen': '#22863a',
    'terminal.ansiBrightYellow': '#b08800',
    'terminal.ansiBrightBlue': '#005cc5',
    'terminal.ansiBrightMagenta': '#5a32a3',
    'terminal.ansiBrightCyan': '#3192aa',
    'terminal.ansiBrightWhite': '#d1d5da',
    'gitDecoration.addedResourceForeground': '#28a745',
    'gitDecoration.modifiedResourceForeground': '#e36209',
    'gitDecoration.deletedResourceForeground': '#d73a49',
    'gitDecoration.untrackedResourceForeground': '#28a745',
    'gitDecoration.ignoredResourceForeground': '#959da5',
    'gitDecoration.conflictingResourceForeground': '#e36209',
    'gitDecoration.submoduleResourceForeground': '#6a737d',
    'debugToolBar.background': '#ffffff',
    'editorGroupHeader.tabsBackground': '#f6f8fa',
    'tab.activeBackground': '#ffffff',
    'tab.activeBorder': '#ffffff',
    'tab.activeBorderTop': '#f9826c',
    'tab.activeForeground': '#24292e',
    'tab.border': '#e1e4e8',
    'tab.hoverBackground': '#ffffff',
    'tab.inactiveBackground': '#f6f8fa',
    'tab.unfocusedHoverBackground': '#f6f8fa',
    'tab.inactiveForeground': '#6a737d',
    'tab.unfocusedActiveBorderTop': '#e1e4e8',
    'tab.unfocusedInactiveForeground': '#6a737d',
    'editorWidget.background': '#f6f8fa',
    'editorWidget.border': '#e1e4e8',
    'editorSuggestWidget.background': '#f6f8fa',
    'editorSuggestWidget.border': '#e1e4e8',
    'editorSuggestWidget.foreground': '#24292e',
    'editorSuggestWidget.highlightForeground': '#0969da',
    'editorSuggestWidget.selectedBackground': '#e1e4e8',
    'editorHoverWidget.background': '#f6f8fa',
    'editorHoverWidget.border': '#e1e4e8',
    'editorHoverWidget.foreground': '#24292e',
    'debugExceptionWidget.background': '#ffeef0',
    'debugExceptionWidget.border': '#d73a49',
    'editorMarkerNavigation.background': '#f6f8fa',
    'editorMarkerNavigationError.background': '#d73a4933',
    'editorMarkerNavigationWarning.background': '#e3620933',
    'editorMarkerNavigationInfo.background': '#0969da33',
    'dropdown.background': '#ffffff',
    'dropdown.border': '#e1e4e8',
    'dropdown.foreground': '#24292e',
    'dropdown.listBackground': '#ffffff',
    'input.background': '#fafbfc',
    'input.border': '#e1e4e8',
    'input.foreground': '#24292e',
    'input.placeholderForeground': '#959da5',
    'inputOption.activeBackground': '#0366d633',
    'inputOption.activeBorder': '#0366d6',
    'inputValidation.errorBackground': '#d73a4933',
    'inputValidation.errorBorder': '#d73a49',
    'inputValidation.errorForeground': '#24292e',
    'inputValidation.infoBackground': '#0366d633',
    'inputValidation.infoBorder': '#0366d6',
    'inputValidation.infoForeground': '#24292e',
    'inputValidation.warningBackground': '#e3620933',
    'inputValidation.warningBorder': '#e36209',
    'inputValidation.warningForeground': '#24292e',
    'list.hoverBackground': '#f6f8fa',
    'list.inactiveSelectionBackground': '#e1e4e8',
    'list.activeSelectionBackground': '#e1e4e8',
    'list.focusBackground': '#cce5ff',
    'list.focusForeground': '#24292e',
    'list.highlightForeground': '#0969da',
    'list.dropBackground': '#cce5ff',
    'list.errorForeground': '#d73a49',
    'list.warningForeground': '#e36209',
    'minimap.background': '#ffffff',
    'minimap.findMatchHighlight': '#ffdf5d',
    'minimap.selectionHighlight': '#c8d1f8',
    'minimap.errorHighlight': '#d73a49',
    'minimap.warningHighlight': '#e36209',
    'minimapGutter.addedBackground': '#28a745',
    'minimapGutter.modifiedBackground': '#e36209',
    'minimapGutter.deletedBackground': '#d73a49',
    'peekView.border': '#0969da',
    'peekViewEditor.background': '#ffffff',
    'peekViewEditor.matchHighlightBackground': '#ffdf5d66',
    'peekViewResult.background': '#ffffff',
    'peekViewResult.fileForeground': '#24292e',
    'peekViewResult.lineForeground': '#6a737d',
    'peekViewResult.matchHighlightBackground': '#ffdf5d66',
    'peekViewResult.selectionBackground': '#e1e4e8',
    'peekViewResult.selectionForeground': '#24292e',
    'peekViewTitle.background': '#ffffff',
    'peekViewTitleDescription.foreground': '#6a737d',
    'peekViewTitleLabel.foreground': '#24292e',
    'pickerGroup.border': '#e1e4e8',
    'pickerGroup.foreground': '#6a737d',
    'quickInput.background': '#f6f8fa',
    'quickInput.foreground': '#24292e',
    'statusBar.background': '#ffffff',
    'statusBar.foreground': '#586069',
    'statusBar.border': '#e1e4e8',
    'statusBar.noFolderBackground': '#ffffff',
    'statusBar.debuggingBackground': '#d73a49',
    'statusBar.debuggingForeground': '#ffffff',
    'statusBarItem.activeBackground': '#24292e33',
    'statusBarItem.hoverBackground': '#24292e44',
    'statusBarItem.prominentBackground': '#e1e4e8',
    'statusBarItem.prominentForeground': '#24292e',
    'statusBarItem.prominentHoverBackground': '#d1d5da',
    'statusBarItem.remoteBackground': '#0969da',
    'statusBarItem.remoteForeground': '#ffffff',
    'titleBar.activeBackground': '#ffffff',
    'titleBar.activeForeground': '#24292e',
    'titleBar.border': '#e1e4e8',
    'titleBar.inactiveBackground': '#f6f8fa',
    'titleBar.inactiveForeground': '#6a737d',
    'menubar.selectionForeground': '#24292e',
    'menubar.selectionBackground': '#e1e4e8',
    'menubar.selectionBorder': '#e1e4e800',
    'menu.foreground': '#24292e',
    'menu.background': '#ffffff',
    'menu.selectionForeground': '#24292e',
    'menu.selectionBackground': '#e1e4e8',
    'menu.selectionBorder': '#e1e4e800',
    'menu.separatorBackground': '#e1e4e8',
    'menu.border': '#e1e4e800',
    'button.background': '#2ea44f',
    'button.foreground': '#ffffff',
    'button.hoverBackground': '#2c974b',
    'button.secondaryBackground': '#fafbfc',
    'button.secondaryForeground': '#24292e',
    'button.secondaryHoverBackground': '#f3f4f6',
    'checkbox.background': '#fafbfc',
    'checkbox.border': '#d1d5da',
    'checkbox.foreground': '#24292e',
    'textLink.foreground': '#0969da',
    'textLink.activeForeground': '#0969da',
    'textCodeBlock.background': '#afb8c133',
    'textBlockQuote.background': '#fafbfc',
    'textBlockQuote.border': '#e1e4e8',
    'textPreformat.foreground': '#586069',
  },
};